### ISSUE TITLE
Disabled class should be set on container

### ISSUE THREAD

**Issue by sir-dunxalot** [knownasilya/ember-cli-toggle#10]
Thanks for the great addon!

If you add 'on' and 'off' text to a toggle and set the toggle to disabled there is not way to style the text without reopening the `x-toggle` component. This is because the `.x-toggle-disabled` class is set on the toggle not the container.

I'd expect a class on the container like `.x-toggle-container-disabled`.

**Comment by knownasilya** [comment]
Would take a PR addressing this issue, since I'm busy this week. Otherwise I'll look into it next week.

**Comment by sir-dunxalot** [comment]
Thanks for the quick response. I'll get a PR up in the next 5-10 mins then.

**Comment by sir-dunxalot** [comment]
[PR up](https://github.com/knownasilya/ember-cli-toggle/pull/11)

**Comment by sir-dunxalot** [comment]
#12

**Comment by knownasilya** [comment]
Published as of fe9c80cfc60ce289dc28f6a74123ee6132a9e5d3
