### ISSUE TITLE
Changes value on insert..

### ISSUE THREAD

**Issue by iUtvikler** [knownasilya/ember-cli-toggle#19]
I have this in my template:

```handlebars
{{x-toggle value=item.enabled class="pull-right"}}
```

Which is bound to this:

```js
{id: 1, enabled: true}
```

But when the page is rendered the value of item is set to false

**Comment by iUtvikler** [comment]
I used toggled instead and that worked.. My bad..

**Comment by knownasilya** [comment]
`{{x-toggle toggled=item.enabled}}` ?

**Comment by iUtvikler** [comment]
@knownasilya yes!

**Comment by gzurbach** [comment]
What's the difference between `toggled` and `value`? I tried both but only `toggled` behaves the way I wat. I was assuming that `toggled` would be the initial state and `value` the binding, but it seems like `toggled` also binds to my property...

**Comment by knownasilya** [comment]
Currently this is hairy, and I plan to rewrite some of this once Ember 2.0 lands, so a major bump would happen here.
