### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defaultTheme' of undefined

### ISSUE THREAD

**Issue by e-karma** [knownasilya/ember-cli-toggle#22]
Thanks for making this!  Having trouble getting it to work in canary and ecli 0.2.0 stock new app

installed with npm install --save-dev ember-cli-toggle

All suggested inputs provided the subject error 
{{x-toggle toggle='startCar'}}
{{x-toggle theme='light' toggle='enableLayer'}}
{{x-toggle theme='ios' size='small' toggle='muteVolume'}}
{{x-toggle theme='flat' toggle='disableTest'}}
{{x-toggle theme='flip' off='Nope' on='Yep' toggle='haveFun'}}
{{x-toggle theme='skewed' size='large' toggle='enablePartyMode'}}

**Comment by knownasilya** [comment]
@e-karma can you provide a stack trace?

**Comment by knownasilya** [comment]
@e-karma give it another try with 0.5.4, I updated to latest ecli.

**Comment by pzuraq** [comment]
Had the same issue, you need to add a `ember-cli-toggle` object to your environment config:

```
'ember-cli-toggle': {
  //includedThemes: ['light', 'ios', 'flip'],
  //excludedThemes: ['flip'],
  //defaultTheme: 'light',
  //defaultSize: 'small'
}
```

Should probably guard against this.

**Comment by knownasilya** [comment]
@pzuraq good catch.
