### ISSUE TITLE
Do not trigger the toggle action at initialization

### ISSUE THREAD

**Issue by pierrickrouxel** [knownasilya/ember-cli-toggle#24]
The component triggers the `toggle` action at initialization. 
I think that isn't a good idea because at this time the position isn't defined by user.

If I want to persist my model directly when the `toggle` action is triggered, I should test if value is different with previous to know if it's well the user who has triggered it.

**Comment by gzurbach** [comment]
+1
Maybe a good solution consist in using one-way binding for the state and use actions only to toggle the state. Data down, actions up!

**Comment by knownasilya** [comment]
@gzurbach yeah that is totally the plan. I'd probably have to release 1.0.

**Comment by gzurbach** [comment]
In case it helps someone, this simple workaround seems enough:
```javascript
// Template
{{x-toggle toggled=defaultFooState toggle='toggleFoo'}}

// Controller
defaultFooState: Ember.computed.readOnly('model.foo')

// Route
toggleFoo(isEnabled) {
  var model = this.get('controller.model');
  if (isEnabled !== model.get('foo')) {
    model.set('foo', isEnabled);
    model.save();
  }
}
```

**Comment by gzurbach** [comment]
@knownasilya Perfect. Your addon is awesome btw!

**Comment by knownasilya** [comment]
Thanks, but it's mainly thanks to the original author of that codepen :+1:

**Comment by knownasilya** [comment]
@gzurbach I've started the work on this branch: https://github.com/knownasilya/ember-cli-toggle/tree/ddau

Feel free to leave comments. I'm felling like the labels are overkill, I wonder how many people use them..

**Comment by gzurbach** [comment]
This looks promising! I agree for the label, and it's mostly a styling issue: users will want to use their own css classes and layout in most cases so they won't use that feature anyways. That said, I think it is important that users can pass an id that will be set on the checkbox so clicking on the label will toggle the button.

**Comment by knownasilya** [comment]
>  I think it is important that users can pass an id that will be set on the checkbox so clicking on the label will toggle the button.

Totally on board.

**Comment by knownasilya** [comment]
Looks like I already support that, just set `forId`.

**Comment by gzurbach** [comment]
I didn't even notice ha! Well :ship: it then!

**Comment by knownasilya** [comment]
This is resolved in master, with the new API.

**Comment by pierrickrouxel** [comment]
Thank you !

**Comment by knownasilya** [comment]
@pierrickrouxel I haven't released to npm yet, so please be my guinea pig :wink:

**Comment by pierrickrouxel** [comment]
Hi @knownasilya.

I try the component from master.

```hbs
{{x-toggle size="small" toggled=model.enabled toggle="toggleDisabled"}}
```

`toggleDisabled` is never triggered.

**Comment by knownasilya** [comment]
@pierrickrouxel it was changed to 'on-toggle'

**Comment by pierrickrouxel** [comment]
Why? It's not a common syntax.

**Comment by knownasilya** [comment]
Should it be `ontoggle`, which is more common, since it's used in the DOM events API.

**Comment by pierrickrouxel** [comment]
In my opinion `toggleˋ was more compliant with ember. By example the default action is ˋaction`, not ˋonaction` no?

**Comment by knownasilya** [comment]
Yeah, but that is changing as `<input type="text" onchange=(action 'updateName')>` becomes possible with 2.0 (1.13?).

**Comment by pierrickrouxel** [comment]
Okay! I read the RFC ˋon-toggle` seems to be good :). Sorry.

**Comment by izukingz** [comment]
Hello, how exactly do i use this feature to disable action trigger on init?

**Comment by knownasilya** [comment]
@izukingz see the comment above: https://github.com/knownasilya/ember-cli-toggle/issues/24#issuecomment-110948784
