### ISSUE TITLE
Uncaught Error: Computed Property declared without a property function

### ISSUE THREAD

**Issue by hoetmaaiers** [knownasilya/ember-cli-toggle#25]
I keep getting this error whenever I add `{{x-toggle}}` to my template. Doesn't matter what options I provide it. Has this anything to do with the new computed property syntax?

Any advice?

**Comment by knownasilya** [comment]
Yes it does. I could revert that commit.

**Comment by hoetmaaiers** [comment]
Do you think thia commit causes my issue?

**Comment by knownasilya** [comment]
What version of Ember are you using?

**Comment by hoetmaaiers** [comment]
I'm using 1.10.0.

**Comment by knownasilya** [comment]
Yeah that would do it. I'll make the change later tonight.

**Comment by knownasilya** [comment]
Give 0.5.8 a try.

**Comment by hoetmaaiers** [comment]
Yep, this solves my issue, thank you.
