### ISSUE TITLE
Theme css files not being pulled in

### ISSUE THREAD

**Issue by bdvholmes** [knownasilya/ember-cli-toggle#30]
I have just started using ember-cli-toggle and I'm finding the css theme files are not getting compiled. If I copy and paste those files into base.css it works.

**Comment by knownasilya** [comment]
Did you specify the theme in the config?

**Comment by bdvholmes** [comment]
No I didn't touch environment variables. Is that required for install?

**Comment by knownasilya** [comment]
The 'default' theme is imported by default, other themes have to be specified in the config.

**Comment by bdvholmes** [comment]
I could be wrong but I don't believe I was even getting the default themes.

**Comment by knownasilya** [comment]
Should be fixed in latest version.

**Comment by bdvholmes** [comment]
Awesome thanks.
