### ISSUE TITLE
Issue setting controller value

### ISSUE THREAD

**Issue by awwester** [knownasilya/ember-cli-toggle#34]
The value on my controller isn't being toggled or bound when changing the switch.

the code I think should work according to the README is `{{x-toggle toggle='onlineOnly' theme='flip' off='All' on='Online'}}`, but the value is not being updated on my controller. Going through the demo and other issues, I've seen other ways such as `toggled=onlineOnly`, `value=onlineOnly`, but none of these seem to be changing the value on my controller. Also have tried variations with to property set as `controller.onlineOnly`. 

On my controller I have either defined the property as `onlineOnly: null,` or I have left off the property.

I'm new to ember and as there aren't other issues around this fundamental problem, I'm guessing I'm doing something wrong, but everything seems right to me according to the available docs.

**Comment by knownasilya** [comment]
Give the latest version a try, it should work.

I accidentally pushed the 1.0 API changes under 0.5.9. I've setup the `0.x` branch which will have the 0.x changes and master will go forward as 1.0.

**Comment by awwester** [comment]
thanks, 0.5.11 works.
