### ISSUE TITLE
Toggle not checked when bound property is true on render? 

### ISSUE THREAD

**Issue by matixmatix** [knownasilya/ember-cli-toggle#35]
` {{x-toggle value=true theme='light'}} ` is rendered in a non-checked state. Is that expected behaviour?

**Comment by knownasilya** [comment]
`toggled` is the attribute you would want.

**Comment by knownasilya** [comment]
The next major version is going to have some API cleanup.

**Comment by matixmatix** [comment]
Thank you @knownasilya. Keep up the good work.
