### ISSUE TITLE
How to differentiate two toggle buttons on same page

### ISSUE THREAD

**Issue by izukingz** [knownasilya/ember-cli-toggle#36]
Is there a way to know which toggle button called the action function. The toggle only has one parameter (isToggeled) so how else can i send the Id of the button that triggered the action?

**Comment by knownasilya** [comment]
Good idea, how about if you received `toggled(isToggled, toggleName) {}` where `name` is set by `{{x-toggle name='first'}}`?

**Comment by izukingz** [comment]
Your suggestion toggled(isToggled, toggleName) should work fine. The workaround will not work in my case since they buttons a dynamically generated with an id for each of them. So i am guessing that {{x-toggle name=controller.someid}} should work alright?

**Comment by knownasilya** [comment]
> So i am guessing that {{x-toggle name=controller.someid}} should work alright?

Exactly.

**Comment by izukingz** [comment]
Oh thanks for the fast response. i just downloaded the addon, and this is what is currently stopping me from using it.

**Comment by knownasilya** [comment]
Ok, I'l let you know once the feature lands (before the end of this week, maybe tomorrow). Stay tuned.

**Comment by izukingz** [comment]
Thanks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Ilya RadchenkoSent: Thursday, August 27, 2015 5:51 PMTo: knownasilya/ember-cli-toggleReply To: knownasilya/ember-cli-toggleCc: izukingzSubject: Re: [ember-cli-toggle] How to differentiate two toggle buttons on same page (#36)Ok, I'l let you know once the feature lands (before the end of this week, maybe tomorrow). Stay tuned.

—Reply to this email directly or view it on GitHub.

**Comment by knownasilya** [comment]
Should be released as v0.6.0. Let me know if it works for you.

**Comment by izukingz** [comment]
Works great. Thanks a lot.
