### ISSUE TITLE
Could not find module `ember-cli-toggle/components/x-toggle/template`

### ISSUE THREAD

**Issue by arunrajasankar** [knownasilya/ember-cli-toggle#37]
Uncaught Error: Could not find module `ember-cli-toggle/components/x-toggle/template` imported from `ember-cli-toggle/components/x-toggle/component`

the above error occurs whenever i try to use {{x-toggle}} component in my application

i tried all of the below:
{{x-toggle toggle='startCar'}}
{{x-toggle theme='light' toggle='enableLayer'}}
{{x-toggle theme='ios' size='small' toggle='muteVolume'}}
{{x-toggle theme='flat' toggle='disableTest'}}
{{x-toggle theme='flip' off='Nope' on='Yep' toggle='haveFun'}}
{{x-toggle theme='skewed' size='large' toggle='enablePartyMode'}}

My ember version is 1.11.1
and Ember Data : 1.0.0-beta.16.1

**Comment by knownasilya** [comment]
What version of toggle are you using?

**Comment by knownasilya** [comment]
Logs like this is related to #33, but the error is better.. I'll try upgrading the Ember CLI version.

**Comment by arunrajasankar** [comment]
ember-cli-toggle version : 0.6.0

**Comment by knownasilya** [comment]
Closing for #33, please post there. It would really help if you could create a bare bones repo that reproduces this issue.

**Comment by knownasilya** [comment]
See if https://github.com/knownasilya/ember-cli-toggle/issues/38 helps
