### ISSUE TITLE
Theme goes blank

### ISSUE THREAD

**Issue by planetcrypton** [knownasilya/ember-cli-toggle#38]
Hi, whenever I use the theme attribute the 'toggle-element' becomes completely blank (as in invisible).
Without defining that attribute the default 'toggle-element' comes up just fine.
(I'm using bootstrap, also without bootstrap the sam occurs)

$ ember -v
version: 1.13.8
node: 0.12.2
npm: 2.13.4
os: darwin x64

**Comment by knownasilya** [comment]
Which version of ember (check chrome console) and which version of the addon?

**Comment by planetcrypton** [comment]
Ember: 1.13.7
"ember-cli-toggle": "^0.6.0"

**Comment by knownasilya** [comment]
Did you import the theme you are changing to? https://github.com/knownasilya/ember-cli-toggle#configuring

**Comment by planetcrypton** [comment]
Yes, I set `includedThemes` in `ENV['ember-cli-toggle']` (other settings work)

**Comment by knownasilya** [comment]
Would love an example of your config and how your toggle is setup so I can try to reproduce.

**Comment by planetcrypton** [comment]
environment.js
`
  var ENV = {
    modulePrefix: 'kfs',
    environment: environment,
    baseURL: '/',
    defaultLocationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },

    cordova: {
      rebuildOnChange: false,
      emulate: false,
      emberUrl: 'http://' + addresses[0] + ':4200',
      liveReload: {
        enabled: false,
        platform: 'ios'
      }
    }
  };

  ENV['ember-cli-toggle'] = {
    includedThemes: ['ios'],
    // excludedThemes: ['flip'],
    defaultShowLabels: true, // defaults to false
    defaultTheme: 'ios',   // defaults to 'default'
    // defaultSize: 'small',    // defaults to 'medium'
    defaultOff: 'Nej',     // defaults to 'Off'
    defaultOn: 'Ja'        // defaults to 'On'
  };
`

settings.hbs
`
<fieldset>
    <legend>Generelt</legend>

    {{#bs-form-group}}
        <label class="control-label">Aktuelt</label>
        {{x-toggle value='controller.aktuelt'}}
    {{/bs-form-group}}

    {{#bs-form-group}}
        <label class="control-label">Nyheder</label>
        {{x-toggle value='controller.nyheder'}}
    {{/bs-form-group}}
</fieldset>

{{outlet}}
`

**Comment by knownasilya** [comment]
`value` should not be quoted. `{{x-toggle value=controller.aktuelt}}`.
Otherwise make sure your bootstrap addon isn't clobbering the toggle CSS.

**Comment by planetcrypton** [comment]
I'm so sorry, it was quoting the value-variable...

**Comment by knownasilya** [comment]
No problem. So it shows up now?

**Comment by planetcrypton** [comment]
nicely :)

**Comment by knownasilya** [comment]
Glad I could help :+1:
