### ISSUE TITLE
Collides with Ember's built-in `on` and `off` methods

### ISSUE THREAD

**Issue by ef4** [knownasilya/ember-cli-toggle#39]
`Ember.Component` has methods named `on` and `off`, which `x-toggle` is attempting to reuse for its own purposes. This fails in confusing ways on some versions of Ember. For example, using Ember 1.13 with x-toggle 0.5.10, the defaults provided in x-toggle are ignored and you end up trying to do `indexOf` on function values.

**Comment by knownasilya** [comment]
Good catch. Will change and release a major version, so it doesn't break anything for those that it works for. Does that sound fine to you?

**Comment by ef4** [comment]
Yes, makes sense. The names were public API, so a major rev is appropriate.

**Comment by ef4** [comment]
I just realized that my workaround for #40 was exacerbating this issue. I was using the XToggle class from the addon directory, and I missed that defaults only get set in the extended class in the app tree.

(It's still bad to squash `on` and `off`, but the squashing _does_ actually work once I figured out why I had no default values.)

**Comment by knownasilya** [comment]
I will still change this and release a new version.
