### ISSUE TITLE
Styles not available when used in an addon

### ISSUE THREAD

**Issue by lolmaus** [knownasilya/ember-cli-toggle#41]
Hi! When I include `ember-cli-toggle` into the main app, it's fine.

But when I instead include it into an addon's `dependencies`, the `x-toggle` component appear unstyled.

PS Thank you for the awesome component!

**Comment by knownasilya** [comment]
I just commited a change, see https://github.com/knownasilya/ember-cli-toggle/blob/master/index.js#L11 Give master a try and let me know if it works, if so I'll release a new version.

**Comment by clevernyyyy** [comment]
@knownasilya - this update works for me.  I was having issues from NPM, but with this update it's good.  Thanks for your hard work & effort!

**Comment by knownasilya** [comment]
Thanks @clevernyyyy, glad it worked for you. I'll release a new version so that npm is a non-issue.
