### ISSUE TITLE
Uncaught Error: Assertion Failed: A helper named 'x-toggle' could not be found

### ISSUE THREAD

**Issue by codecalypso** [knownasilya/ember-cli-toggle#46]
I not sure why I am getting this error in a my application. Is it because I haven't added the line below to a config file. I am new to Ember and am not sure where I'd add that information. Do I add it to environment.js or create a new file in the config folder? I am currently using Ember 2.5.1

**Add a configuration for ember-cli-toggle to include only the themes that you will use.**

ENV['ember-cli-toggle'] = {
  includedThemes: ['light', 'default', 'flip'],
  excludedThemes: ['flip'],
  defaultShowLabels: true, // defaults to false 
  defaultTheme: 'light',   // defaults to 'default' 
  defaultSize: 'small',    // defaults to 'medium' 
  defaultOffLabel: 'False',     // defaults to 'Off' 
  defaultOnLabel: 'True'        // defaults to 'On' 
};

**Comment by knownasilya** [comment]
the config should be in `config/environment.js`. Did you restart your `ember serve` after installing addon?

**Comment by codecalypso** [comment]
I did. I ran this: npm install ember-cli-toggle and then added this {{x-toggle value=myValue onToggle=(mut myValue)}} to my template

**Comment by knownasilya** [comment]
`ember install ember-cli-toggle`

**Comment by codecalypso** [comment]
Yeah! Thanks so much, that worked 👍

**Comment by knownasilya** [comment]
Glad I could help!
