### ISSUE TITLE
the value only supports the string "True", not the boolean true

### ISSUE THREAD

**Issue by skaterdav85** [knownasilya/ember-cli-toggle#51]
Hi! I'm doing something like this:

``` hbs
{{x-toggle value=tfa onToggle=(mut tfa)}}
```

When `tfa` is boolean `true`, the toggle is in the off state, but when `tfa` is the string `"True"`, it is in the on state. If `tfa` is any other string, it is also off. Is this intentional, or is this a bug?

**Comment by checkerap** [comment]
It seams by design, as the default values for 'on' 'off' are strings: 'True', 'False'.

If you change them in config:

ENV['ember-cli-toggle'] = {    
defaultOffLabel: false,    
defaultOnLabel: true    
}



than it seams to work with true, false

**Comment by knownasilya** [comment]
Sorry, I missed this. Yes you can change the values to suit your needs.
