### ISSUE TITLE
Depreciation in Ember 2.8

### ISSUE THREAD

**Issue by aklkv** [knownasilya/ember-cli-toggle#52]
DEPRECATION: Enumerable#contains is deprecated, use Enumerable#includes instead. [deprecation id: ember-runtime.enumerable-contains] See http://emberjs.com/deprecations/v2.x#toc_enumerable-contains for more details.

**Comment by realityendshere** [comment]
Thanks for patching this! Would it be possible to tag and publish this as v2.0.2? Is there still work to be done before this patch can be referenced by version?

**Comment by knownasilya** [comment]
I'll try to release a new version this week. Thanks for the ping.

**Comment by vluoto** [comment]
Thanks for the patch! I'm too still waiting for the patch to be released though. :v:

**Comment by knownasilya** [comment]
On it 😄

**Comment by knownasilya** [comment]
Published v2.0.2

**Comment by vluoto** [comment]
🎉
