### ISSUE TITLE
How to work with booleans?

### ISSUE THREAD

**Issue by matixmatix** [knownasilya/ember-cli-toggle#55]
I'm having difficulties getting this to work with toggling booleans.

component:
```
...
booleanValue: false,
...
```

template:
````
my value: {{booleanValue}}
{{x-toggle value=booleanValue onToggle=(mut booleanValue) theme='light' size='large'}}
```

.. then the output is either `my value: on` or `my value: off`. Is it possible to simply toggle between `true` and `false`?

**Comment by knownasilya** [comment]
See the first example here https://github.com/knownasilya/ember-cli-toggle#labels

**Comment by matixmatix** [comment]
@knownasilya thank you, this works. In my opinion, this API is fairly unintuitive and unusual. To set possible toggle values in a string, and pass it in a property named `onLabel/offLabel` just seems kinda odd. I'm wondering what led you to this decision in the latest major release? On the other hand, thanks a lot for making and maintaining this add-on, I use it in a couple of projects.

**Comment by knownasilya** [comment]
Mainly it was from a contributors PR. I'm open for alternatives.
