### ISSUE TITLE
Doesn't work in 2.10

### ISSUE THREAD

**Issue by sibijohn72** [knownasilya/ember-cli-toggle#59]
It simply doesnt work in 2.10. I tried to set up a minimal toggle button in a new project but nothing happens to the button when i click. It does not toggle.

**Comment by knownasilya** [comment]
Thanks, will investigate.

**Comment by lancedikson** [comment]
@sibijohn72, could you provide some code? It would be nice to see on using of the component and your config for it at `environment.js` if it exists.

**Comment by lancedikson** [comment]
Btw, for me, it works well on 2.10.

**Comment by cibernox** [comment]
I can reproduce in 2.11. The problem seems to be that this component incorrectly call the `onToggle` function on init, causing the dread`"Assertion Failed: You modified "v1" twice on <dummy@controller:application::ember294> in a single render`.

I'm investigating a fix.

**Comment by lancedikson** [comment]
@cibernox, could you provide the code as well? Let us know how do you actually use the `x-toggle`  component, please :)

**Comment by cibernox** [comment]
@lancedikson No need. The very test suite is a good example of the bug: https://travis-ci.org/knownasilya/ember-cli-toggle/jobs/196596235

**Comment by avanov** [comment]
What's the status of this issue? I've tried using it with `ember-cli 2.11.1`, and I so no widget when I use the component (no errors in console though).

**Comment by knownasilya** [comment]
Did you try version 3.0?

**Comment by avanov** [comment]
@knownasilya yes, the latest one available on npm

**Comment by avanov** [comment]
@knownasilya the default theme works
```
{{x-toggle
  value=newUsersOnlyToggle
  showLabels=true
  onLabel='Enabled::true'
  offLabel='Disabled::false'
  onToggle=(mut newUsersOnlyToggle)
}}
```
but then, as soon as I specify the `theme` attribute, the widget renders only labels, without the control.

**Comment by avanov** [comment]
@knownasilya yes, the latest one available on npm.

It turned out, that the default theme works fine
```
{{x-toggle
  value=myValue
  showLabels=true
  onLabel='Enabled::true'
  offLabel='Disabled::false'
  onToggle=(mut myValue)
}}
```
but then, as soon as I specify a non-default `theme` attribute, the widget renders only labels, without the control.

**Comment by knownasilya** [comment]
You must opt into other themes, see the configuration section in the readme.
