### ISSUE TITLE
Conditional styles importing

### ISSUE THREAD

**Issue by lancedikson** [knownasilya/ember-cli-toggle#60]
Looks like there are some cases when you want a customized toggle and don't need those default styles. Is it suitable to make them importable optionally like add `@import 'ember-cli-toggle'` to the `app.css`?

**Comment by knownasilya** [comment]
Sure, as long as that is set by default.

**Comment by lancedikson** [comment]
@knownasilya, I have a good example of that practice — [ember-power-select](https://github.com/cibernox/ember-power-select/blob/a8e1192ed055795239b2eb856e937a575c0b2776/index.js#L25), but they do it with adding [some complexity](https://github.com/cibernox/ember-power-select/blob/a8e1192ed055795239b2eb856e937a575c0b2776/config/release.js#L17) to addon's release process. They just have some `ember release` command that precompiles all sass to vendor's CSS, creates a new minor version of the addon and push it, I guess. 
But, it's cool that this way has backward compatibility and doesn't push people to install Sass to have any styles.
What do you think? Is it comfortable to have a complicated way to release?

**Comment by knownasilya** [comment]
We already do that, see https://github.com/knownasilya/ember-cli-toggle/blob/master/index.js#L36

**Comment by lancedikson** [comment]
But `base.css` includes anyway without any condition, right?

**Comment by knownasilya** [comment]
Yeah, we could add a property to exclude it, e.g. `excludeBaseStyles: true`.

**Comment by lancedikson** [comment]
Sounds good 👍

**Comment by knownasilya** [comment]
This is a thing in v3.0.0.
