### ISSUE TITLE
README example causes ember error

### ISSUE THREAD

**Issue by vmalloc** [knownasilya/ember-cli-toggle#61]
Trying to create a simple controller with a boolean `flag` attribute, and the code:

```
{{x-toggle value=flag onToggle=(mut flag)}}
```
As taken from the README, Ember raises an error:

```
Assertion Failed: You modified flag twice on <webapp@controller:session/index::ember903> in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
```

Tested with latest ember-cli-toggle (v2.0.2) and Ember 2.10

**Comment by knownasilya** [comment]
Thanks for reporting.

**Comment by hoboman313** [comment]
I'm running into the same issue on emberjs 2.10.2. Happens during the initial load.
The stack trace of the failure is on the x-toggle component: line 47 -> 182

**Comment by hoboman313** [comment]
Also I noticed that the double rendering issue happens only when the initial value is false.

**Comment by knownasilya** [comment]
Not undefined?

**Comment by hoboman313** [comment]
correct

**Comment by hoboman313** [comment]
Might have been an error on my side as I copied the example which was (mut myValue) instead of (action (mut myValue))

**Comment by knownasilya** [comment]
Give v3.0.0 a try.
