### ISSUE TITLE
how to disable switch?

### ISSUE THREAD

**Issue by dezudas** [knownasilya/ember-cli-toggle#9]
How can I disable the switch, for the user who don't have the edit access.

**Comment by knownasilya** [comment]
@dezudas not currently supported, but I'll see what I can do :+1:  Thanks!

**Comment by knownasilya** [comment]
Added https://github.com/knownasilya/ember-cli-toggle/releases/tag/v0.5.0

**Comment by dezudas** [comment]
Thanks @knownasilya  that was great help
